- name: Install Ubuntu on RK1
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars/vault.yml
  vars:
    download_url: https://firmware.turingpi.com/turing-rk1/ubuntu_22.04_rockchip_linux/v1.33/ubuntu-22.04.3-preinstalled-server-arm64-turing-rk1_v1.33.img.xz
    compressed_image_path: ./Downloads/ubuntu-22.04.3-preinstalled-server-arm64-turing-rk1_v1.33.img.xz
    extracted_image_path: ./Downloads/ubuntu-22.04.3-preinstalled-server-arm64-turing-rk1_v1.33.img
  tasks:
    - name: make sure tpi installed
      become: yes
      apt:
        deb: https://firmware.turingpi.com/tpi/debian/tpi_1.0.5-1_amd64.deb

    - name: Install xz
      become: yes
      apt:
        pkg:
          - xz-utils

    - name: Download Ubuntu image for RK1
      get_url:
        url: "{{ download_url }}"
        dest: "{{ compressed_image_path }}"
        mode: 0644

    - name: Extract xz archive
      command:
        cmd: "unxz --keep {{ compressed_image_path }}"
        creates: "{{ extracted_image_path }}"

    - name: Get hosts from turingpinodes group
      set_fact:
        turingpi_hosts: "{{ groups['turingpinodes'] | default([]) }}"

    - name: Display number of nodes found
      debug:
        msg: "Found {{ turingpi_hosts | length }} nodes in the turingpinodes group"

    - name: Process each node in turingpinodes group
      block:
        - name: Customize image for each node
          include_tasks: customize_image.yml
          loop: "{{ turingpi_hosts }}"
          loop_control:
            loop_var: item
          vars:
            image_path: "{{ extracted_image_path }}"
      when: turingpi_hosts | length > 0

    - name: Notify if no nodes found
      debug:
        msg: "No nodes found in the turingpinodes group"
      when: turingpi_hosts | length == 0
